
import { User, UserData, Position, Trade, Drawing } from '../types';

// CONFIGURATION: Set this to true to use the backend/server.js API (Running on localhost:5000)
const USE_REAL_BACKEND = false; 
const API_URL = 'http://localhost:5000/api';

// Mock "Database" keys for LocalStorage Mode
const DB_USERS = 'tm_users_db';
const DB_DATA_PREFIX = 'tm_user_data_';

interface StoredUser {
    id: string;
    email: string;
    passwordHash: string;
    name: string;
    avatar?: string;
}

const delay = (ms: number) => new Promise(res => setTimeout(res, ms));

class AuthService {
    
    // --- REAL BACKEND METHODS (Use these if USE_REAL_BACKEND is true) ---

    private async apiCall(endpoint: string, method: string, body?: any) {
        const token = localStorage.getItem('trade_jwt_token');
        const headers: any = { 'Content-Type': 'application/json' };
        if (token) headers['Authorization'] = token;

        const response = await fetch(`${API_URL}${endpoint}`, {
            method,
            headers,
            body: body ? JSON.stringify(body) : undefined
        });

        const data = await response.json();
        if (!response.ok) throw new Error(data.message || 'API Error');
        return data;
    }

    // --- HYBRID AUTHENTICATION ---

    public async checkEmailExists(email: string): Promise<boolean> {
        if (USE_REAL_BACKEND) {
            // Real backend handles check during signup usually
            return false; 
        }
        await delay(500);
        const users = this.getUsersLocal();
        return users.some(u => u.email === email);
    }

    public async login(email: string, password: string): Promise<User> {
        if (USE_REAL_BACKEND) {
            const res = await this.apiCall('/auth/login', 'POST', { email, password });
            localStorage.setItem('trade_jwt_token', res.token);
            this.saveUserDataLocal(res.user.id, res.data); // Cache locally
            return res.user;
        }

        await delay(800);
        const users = this.getUsersLocal();
        const user = users.find(u => u.email === email && u.passwordHash === btoa(password));
        
        if (!user) throw new Error('Invalid email or password');
        
        return {
            id: user.id,
            email: user.email,
            name: user.name,
            avatar: user.avatar,
            token: 'mock-jwt-' + Date.now()
        };
    }

    public async initiateSignup(email: string, password: string, name: string): Promise<void> {
        if (USE_REAL_BACKEND) {
            await this.apiCall('/auth/signup', 'POST', { email, password, name });
            return;
        }
        // Local mode: Do nothing, wait for verify
    }

    public async verifyAndRegister(email: string, password: string, name: string, otp: string): Promise<User> {
        if (USE_REAL_BACKEND) {
            const res = await this.apiCall('/auth/verify', 'POST', { email, otp });
            localStorage.setItem('trade_jwt_token', res.token);
            this.saveUserDataLocal(res.user.id, res.data);
            return res.user;
        }

        // Local Mode Registration
        const newUser: StoredUser = {
            id: 'u_' + Date.now(),
            email,
            passwordHash: btoa(password),
            name,
            avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`
        };

        this.saveUserLocal(newUser);
        
        // Initialize Data
        this.saveUserDataLocal(newUser.id, {
            userId: newUser.id,
            balance: 100000,
            positions: [],
            history: [],
            drawings: []
        });

        return {
            id: newUser.id,
            email: newUser.email,
            name: newUser.name,
            avatar: newUser.avatar,
            token: 'mock-jwt-' + Date.now()
        };
    }

    // --- OTP LOGIC ---
    public async generateOTP(email: string): Promise<string> {
        if (USE_REAL_BACKEND) {
            // OTP is generated by server in initiateSignup step
            return 'WAITING_FOR_SERVER'; 
        }

        await delay(600);
        const otp = '100';
        // Simulation for frontend demo
        console.log(`[SMTP MOCK] Sending email to ${email} with OTP: ${otp}`);
        alert(`[DEMO EMAIL] Verification Code for ${email}: ${otp}`);
        return otp;
    }

    // --- GOOGLE AUTH MOCK ---
    public async googleLogin(email: string, name: string): Promise<User> {
        await delay(1000);
        const users = this.getUsersLocal();
        let user = users.find(u => u.email === email);

        if (!user) {
            user = {
                id: 'g_' + Date.now(),
                email,
                passwordHash: 'google-oauth-mock',
                name,
                avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`
            };
            this.saveUserLocal(user);
            this.saveUserDataLocal(user.id, {
                userId: user.id,
                balance: 100000,
                positions: [],
                history: [],
                drawings: []
            });
        }

        return {
            id: user.id,
            email: user.email,
            name: user.name,
            avatar: user.avatar,
            token: 'mock-jwt-' + Date.now()
        };
    }

    // --- DATA PERSISTENCE ---

    public getUserData(userId: string): UserData {
        // Always try local cache first for speed
        const key = DB_DATA_PREFIX + userId;
        const json = localStorage.getItem(key);
        if (json) return JSON.parse(json);
        
        return {
            userId,
            balance: 100000,
            positions: [],
            history: [],
            drawings: []
        };
    }

    public async saveUserData(userId: string, data: UserData): Promise<void> {
        this.saveUserDataLocal(userId, data);
        
        if (USE_REAL_BACKEND) {
            // Background sync
            try {
                await this.apiCall('/user/sync', 'POST', data);
            } catch (e) {
                console.warn("Failed to sync with cloud", e);
            }
        }
    }

    // --- LOCAL STORAGE HELPERS ---

    private getUsersLocal(): StoredUser[] {
        const json = localStorage.getItem(DB_USERS);
        return json ? JSON.parse(json) : [];
    }

    private saveUserLocal(user: StoredUser) {
        const users = this.getUsersLocal();
        users.push(user);
        localStorage.setItem(DB_USERS, JSON.stringify(users));
    }

    private saveUserDataLocal(userId: string, data: UserData): void {
        const key = DB_DATA_PREFIX + userId;
        localStorage.setItem(key, JSON.stringify(data));
    }
}

export const authService = new AuthService();
